import { readFileSync, writeFileSync } from 'node:fs'

const origin = 'https://github.com/aitofy-dev/jev-awesome-skills'
const raw = 'https://raw.githubusercontent.com/aitofy-dev/jev-awesome-skills/main'

const skills = [
  ['jev-awesome-skills', 'When to call Jev, fail open, and the proceed / ask / stop cutoffs.'],
  ['jev-gate', 'Proceed, ask, or stop when the repo may already decide a closed choice.'],
  ['jev-route', 'Pick one installed skill or tool, or none.'],
  ['jev-guard', 'Before a command that might destroy data, leak a secret, or leave the task.'],
  ['jev-verify', 'Before reporting a claim or done.'],
  ['jev-triage', 'One label for a record you already have.'],
  ['jev-review', 'Ship, fix, or ask a person. Does not merge.'],
  ['jev-act', 'Next action from a list you observed. No invented clicks.'],
]

const link = (name, note) =>
  `- [${name}](${origin}/blob/main/skills/${name}/SKILL.md): ${note} Raw: ${raw}/skills/${name}/SKILL.md`

const llms = `# Jev awesome skills

> Open-source TypeSafe Jev (System One) skills for coding agents. Closed choice, noul, and score judgments. The host writes the code. Jev returns probabilities only: proceed, ask, or stop.

People find this as a Jev skill for Claude Code, Codex, Cursor, or Grok, and as an awesome Jev catalog. It is not the official TypeSafe skill, and it does not invent star counts or accuracy numbers.

Install today from Git: \`npm i github:aitofy-dev/jev-awesome-skills\`. The npm name is \`@aitofy/jev-awesome-skills\`. Dry-run needs no API key. A live call reads the environment variable TYPESAFE_API_KEY and must not print it.

## Docs

- [README](${origin}/blob/main/README.md): what it is, install, one offline example. Raw: ${raw}/README.md
- [llms-full.txt](${raw}/llms-full.txt): this index, the README, and every skill in one file.
- [Changelog](${origin}/blob/main/CHANGELOG.md)

## Skills

${skills.map(([name, note]) => link(name, note)).join('\n')}

## Examples

- [Gate request](${raw}/examples/gate.request.json)
- [Gate fixture, branch proceed](${raw}/examples/gate.response.json)
- [Route fixture, branch ask](${raw}/examples/route.response.json)
- [Guard fixture, branch stop](${raw}/examples/guard.response.json)
`

writeFileSync(new URL('../llms.txt', import.meta.url), `${llms.trim()}\n`)

const files = [
  'README.md',
  'llms.txt',
  'CHANGELOG.md',
  ...skills.map(([name]) => `skills/${name}/SKILL.md`),
]
const full = [
  '# @aitofy/jev-awesome-skills',
  '',
  'Full text for language models. Generated by scripts/llms.mjs. Do not edit by hand.',
  '',
  ...files.flatMap((file) => ['', `----- ${file} -----`, '', readFileSync(new URL(`../${file}`, import.meta.url), 'utf8').trim(), '']),
].join('\n')
writeFileSync(new URL('../llms-full.txt', import.meta.url), `${full.trim()}\n`)
